### ISSUE TITLE
tsc -b triggers webpack to rebuild the whole app

### ISSUE THREAD

**Issue by IIIristraM** [IIIristraM/lerna-ts#1]
The reason is in the current `tsc` behaviour
https://github.com/microsoft/TypeScript/issues/35340

**Comment by IIIristraM** [comment]
replace tsc with ts-loader

**Comment by dko-slapdash** [comment]
@IIIristraM It's not always possible to replace tsc with ts-loader. Imagine there is a large monorepo where e.g. packages/package1/src/a.ts refers to another packages/package2/dist/abc file (assuming dist/ folder has abc.js, abc.d.ts and abc*.map files). The packages are built and watched independently by tsc, so there is really no place for ts-loader in this schema (webpack's input is compiled *.js files).

So, in the above case, a change in packages/package2/src/*.ts file(s) which causes no changes in packages/package2/dist/abc.* files would trigger webpack rebuild, because tsc writes back even unchanged result files.
